### ISSUE TITLE
开启No-Fun Mode后无法访问

### ISSUE THREAD

**Issue by yushizui** [hibikikuze4dan/lanraragi-react-web#8]
用安卓那个客户端可以访问

**Comment by hibikikuze4dan** [comment]
Just a heads up that I don't know how to read Chinese so I used Google translate, so forgive me if I get your issue wrong but you're saying that the app doesn't work with No-Fun Mode enabled from the Lanraragi app? I just checked what happens when you turn No-Fun Mode on and then use Lanraragi-React-Web and it looks like while you can see archive information as long as you've provided an api key (make sure that it is base64 encoded), you can't see the images (thumbnails and archive images). This is mainly due to how the requests for the images are made since all that's done is just passing the image url to an img html tag as the src property. Since there are no headers being passed the image request is denied by Lanraragi.

This may take a minute to fix, so if you really want to use this app for now I would recommend not using No-Fun Mode.

**Comment by hibikikuze4dan** [comment]
Well, good news. This was easier to fix than I expected. Just pushed up [a commit](https://github.com/hibikikuze4dan/lanraragi-react-web/commit/d212ea534eaa5839ea9e4b66265e136d77d5713b) that should fix the issue. Update your docker image and rebuild the container and as long as you provide a base64 encoded API password that matches the one you use for your Lanraragi instance you should be able to use the app fully with no more problems. Let me know if you face any more issues.

**Comment by yushizui** [comment]
I can access it normally now. Before, it was actually because the api key was not base64 encoded. But now I have discovered a more serious problem. The reason is that when I use lrr react and then use lchaival (Android client), it will cause a crash. Then I checked and found that it was the comics. After rating, all tags of the comic have changed, and a space has been added to all tags, for example, language:chinese has changed to language: chinese.

**Comment by hibikikuze4dan** [comment]
Just pushed up another commit that should prevent that issue from happening in the future. Also added a setting for whether or not No-Fun Mode is enabled which will determine how images are rendered (as a blob or using the src itself).

**Comment by yushizui** [comment]
Thank you for your efforts. I just tried it on my Android phone. It seems that there is something wrong with the image display. The "Display method for images when reading an archive" does not work.

**Comment by hibikikuze4dan** [comment]
Can't seem to reproduce that behavior on my end. What kind of archive are you reading (cbz, zip, pdf)? Do you have an example video or would you share the name of the archive to see if I can find a copy of my own to test with?

**Comment by yushizui** [comment]
Most of the files I use are .zip, and most of the downloaded images are high-resolution original images. This is how it looks when opened in a mobile browser, with part of the image on the screen.
![12](https://github.com/hibikikuze4dan/lanraragi-react-web/assets/130179532/9453920b-62e9-4617-b9d4-0361451fc1b5)

**Comment by hibikikuze4dan** [comment]
What browser are you using and at what version? Maybe this is a CSS compatibility issue.

**Comment by yushizui** [comment]
Just updated chrome to the latest version and the problem still exists

**Comment by hibikikuze4dan** [comment]
Then maybe it's a rerendering issue? Like the image itself isn't updating when applying the object-fit property to it. I pushed up a new update a few hours ago that forces the image to do a rendering once it has completely loaded. See if that fixes the issue.

**Comment by yushizui** [comment]
Sorry, I updated it and the situation is still the same, and I changed my phone and the situation is the same

**Comment by hibikikuze4dan** [comment]
I have to apologize as well. I can't actually reproduce this issue on my end, so that's what is making it hard to actually fix. The largest images in my archives are around 1500 x 2200. What is the pixel size of the images you are displaying?

**Comment by chu-shen** [comment]
> Most of the files I use are .zip, and most of the downloaded images are high-resolution original images. This is how it looks when opened in a mobile browser, with part of the image on the screen. 

image settings -> display method -> **contain**
试试改成  **contain**

chrome browser version higher than 114?
chrome 版本要高于 114

If you have any more questions, you can record a screen capture/screenshot, upload the settings and the compressed file.
还有问题的话可以录屏/截图，发下设置和压缩包

---

@hibikikuze4dan 
When rating, the following error occurred: "Failed to load resource: the server responded with a status of 401 (Unauthorized)"

Missing api key: 
https://github.com/hibikikuze4dan/lanraragi-react-web/blob/bec180292d28bb2bf2b7fae6e49f22506fd40b64/src/requests/metadata.js#L20

**Comment by yushizui** [comment]
chrome版本是119，display method已经设置为contain，而且我换其他安卓手机也一样，我怀疑是不是以为我开启的是No-Fun Mode有关，只有这一点我可能和你们不一样
The chrome version is 119, the display method has been set to contain, and it is the same when I switch to other Android phones. I wonder if it is related to thinking that I have turned on No-Fun Mode. I may be different from you on this point.

**Comment by hibikikuze4dan** [comment]
@chu-shen thanks for pointing that out. All requests should now make a function call to get the api key before making a request.

@yushizui I was still unable to reproduce the issue you reported even after turning on No-Fun Mode and restarting Lanraragi.

**Comment by yushizui** [comment]
> @chu-shen thanks for pointing that out. All requests should now make a function call to get the api key before making a request.
> 
> @yushizui I was still unable to reproduce the issue you reported even after turning on No-Fun Mode and restarting Lanraragi.

更新最新版本后问题解决
Problem solved after updating to latest version
